security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
google:
  client:
    clientId: 156075602639-bhbocn020fbv6lfmi3qb7s3a5f8efk25.apps.googleusercontent.com
    clientSecret: fLvSXXpy3-xVAA64honmVGsY
    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    redirectURI: localhost:8080/oauth/google/callback
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: profile email
  resource:
    userInfoUri: https://www.googleapis.com/userinfo/v2/me
    prefer-token-info: false
github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

#logging:
#  level:
#    org.springframework.security: DEBUG
#

#Mongo DB Configuration
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dnetwork